FROM python:3.13-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
WORKDIR /app
COPY pyproject.toml .
RUN uv sync

COPY src ./src
WORKDIR ./src

EXPOSE 6339
CMD ["uv", "run", "fastapi", "run", "--port", "6339", "server.py"]
