version: "3.9"

services:
  fastapi:
    depends_on:
      - mlflow
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_app
    ports:
      - "6339:6339"
    volumes:
      - ./src:/app/src
    environment:
      - UV_SYSTEM_PYTHON=1
      - MLFLOW_TRACKING_URI=http://mlflow:8080

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_app
    ports:
      - "8080:8080"
    volumes:
      - ./mlruns:/mlruns/run
    environment:
      - UV_SYSTEM_PYTHON=1
